<a href="https://colab.research.google.com/github/AlexGryshovenko/github-for-studing/blob/main/Intro_to_Numpy_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Завдання
## 1. Створити двомірний нульовий масив розміром 11х11 та заповнити його діагоналі одиницями.

1.1. Задати розмір масиву

In [ ]:
import numpy as np

In [ ]:
size = 8

1.2. Створити нульовий масив заданого розміру

In [ ]:
arr = np.zeros([size, size])

1.3 Надрукувати створений масив

In [ ]:
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


1.4 Змінити діагоналі за допомогою двох циклів

In [ ]:
for i in range(size):
	for j in range(size):
		if (i==j):
			arr[i][j] = 1
		elif (j==size-i-1):
			arr[j][i] = 1

1.5 Вивести створений масив

In [ ]:
print(arr)

[[1. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 1. 0. 0. 0.]
 [0. 0. 0. 1. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 1.]]


## 2. Засобами NumPy створити вертикальні та горизонтальні зображення градієнту в обидва боки (поступове збільшення яскравості на зображенні).

Приклад зображення градієнту
<img src="https://github.com/mosolab/DIP/blob/master/assignments/horizontal_grad.jpg?raw=1" height="200" width="200">

In [ ]:
import cv2
import numpy as np

### Горизонтальний градієнт

2.1 Створити нульовий масив розміром 255х255

In [ ]:
size = 255
horizontal_gradient1 = np.zeros([size, size])

2.2 Визначити розміри масиву

In [ ]:
w = horizontal_gradient1.shape[1]
h = horizontal_gradient1.shape[0]

2.3 Поелементно змінити яскравості кожного пікселя

In [ ]:
for i in range(size):
    for j in range(size):
        horizontal_gradient1[j][i] = i

2.4 Записати зображення засабами OpenCV

In [ ]:
cv2.imwrite('horizontal_grad1.jpg', horizontal_gradient1)

True

2.5 Аналогічно створити горизонтальний градієнт в інший бік

In [ ]:
size = 255
horizontal_gradient2 = np.zeros([size, size])

w = horizontal_gradient2.shape[1]
h = horizontal_gradient2.shape[0]
for i in range(size):
    for j in range(size):
        horizontal_gradient2[size-1-j][size-1-i] = i
        
cv2.imwrite('horizontal_grad2.jpg', horizontal_gradient2)

True

### Вертикальний градієнт

2.6 Створити нульовий масив розміром 255х255

In [ ]:
vertical_gradient1 = np.zeros([size, size])

2.7 Визначити розміри масиву

In [ ]:
w = vertical_gradient1.shape[1]
h = vertical_gradient1.shape[0]

2.8 Поелементно змінити яскравості кожного пікселя

In [ ]:
for i in range(h):
    for j in range(w):
        vertical_gradient1[i][j] = i

2.9 Записати зображення засабами OpenCV

In [ ]:
cv2.imwrite('vertical_grad1.jpg', vertical_gradient1)

True

2.10 Аналогічно створити горизонтальний градієнт в інший бік

In [ ]:
vertical_gradient2 = np.zeros([size, size])

w = vertical_gradient2.shape[1]
h = vertical_gradient2.shape[0]

for i in range(size):
    for j in range(size):
        vertical_gradient2[size-1-i][size-1-j] = i
        
cv2.imwrite('vertical_grad2.jpg', vertical_gradient2)


True